// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_NOJgB425rk89CVwVeqvqsXe9sMZymFk',
    appId: '1:73078824026:web:1215f9a74fc7cd4d55cc63',
    messagingSenderId: '73078824026',
    projectId: 'fieldtrack-pro-a16b4',
    authDomain: 'fieldtrack-pro-a16b4.firebaseapp.com',
    storageBucket: 'fieldtrack-pro-a16b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIulGv_v_1Q8JcirF5Eo3SMITjHT1Mwv8',
    appId: '1:73078824026:android:23f76532b90e910155cc63',
    messagingSenderId: '73078824026',
    projectId: 'fieldtrack-pro-a16b4',
    storageBucket: 'fieldtrack-pro-a16b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJBvWugJ70DaHL8dXhMfqcEf2u1q1i7yQ',
    appId: '1:73078824026:ios:9078fdee95aa347a55cc63',
    messagingSenderId: '73078824026',
    projectId: 'fieldtrack-pro-a16b4',
    storageBucket: 'fieldtrack-pro-a16b4.firebasestorage.app',
    iosBundleId: 'com.example.fieldTrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJBvWugJ70DaHL8dXhMfqcEf2u1q1i7yQ',
    appId: '1:73078824026:ios:9078fdee95aa347a55cc63',
    messagingSenderId: '73078824026',
    projectId: 'fieldtrack-pro-a16b4',
    storageBucket: 'fieldtrack-pro-a16b4.firebasestorage.app',
    iosBundleId: 'com.example.fieldTrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_NOJgB425rk89CVwVeqvqsXe9sMZymFk',
    appId: '1:73078824026:web:2582865b776daf2a55cc63',
    messagingSenderId: '73078824026',
    projectId: 'fieldtrack-pro-a16b4',
    authDomain: 'fieldtrack-pro-a16b4.firebaseapp.com',
    storageBucket: 'fieldtrack-pro-a16b4.firebasestorage.app',
  );
}
